[evaders]
align_control_mode = "share"
angle_noise = 0.0
w_align = 0.15
w_goal = 1.2
w_avoid = 1.5
w_explore = 0.4
soc_enabled = true
soc_mode = "v4_varh"
soc_relax_to_w_align = true
soc_stress_decay = 0.05
soc_surprise_gain = 0.0
soc_threat_gain = 0.0
soc_threshold = 1.0
soc_release = 0.0
soc_neighbor_coupling = 0.0
soc_align_drop = 0.0
soc_align_relax = 0.02
soc_align_min = 0.05
soc_align_max = 0.95
soc_topple_noise = 0.0
soc_entropy_gain = 0.0
soc_entropy_ema_alpha = 0.15
soc_heading_bins = 36
soc_heading_smoothing = 0.5
soc_heading_decay = 0.01
soc_varh_target = 0.04
soc_varh_gain = 0.5
soc_varh_deadband = 0.001

[pursuers]
policy = "p1_intercept"
intercept_gain = 0.75
intercept_tmax = 0.0
