[evaders]
align_control_mode = "share"
angle_noise = 0.0
w_align = 0.15
w_goal = 1.2
w_avoid = 1.5
w_explore = 0.4
soc_enabled = true
soc_stress_decay = 0.08
soc_surprise_gain = 0.3
soc_threat_gain = 0.35
soc_threshold = 0.5
soc_release = 0.25
soc_neighbor_coupling = 0.05
soc_align_drop = 0.15
soc_align_relax = 0.0
soc_align_min = 0.05
soc_align_max = 0.95
soc_topple_noise = 0.12

[pursuers]
policy = "p1_intercept"
